SET SERVEROUTPUT ON

DECLARE
nota NUMBER(3,1):=8.5;

BEGIN

CASE

WHEN nota < 5 AND nota >= 0 THEN 
	DBMS_OUTPUT.PUT_LINE('Suspenso');
WHEN nota >= 5 AND nota <7 THEN
	DBMS_OUTPUT.PUT_LINE('Aprobado');
WHEN nota >=7 AND nota <9 THEN 
	DBMS_OUTPUT.PUT_LINE('Notable');
WHEN nota >=9 AND nota <= 10 THEN 
	DBMS_OUTPUT.PUT_LINE('SOBRESALIENTE');
ELSE 
	DBMS_OUTPUT.PUT_LINE('Nota incorrecta');

END CASE;

END;
/